CREATE DATABASE IF NOT EXISTS reddit_authdb;
CREATE DATABASE IF NOT EXISTS reddit_userdb;
CREATE DATABASE IF NOT EXISTS reddit_postdb;
CREATE DATABASE IF NOT EXISTS reddit_feeddb;
CREATE DATABASE IF NOT EXISTS reddit_votedb;
CREATE DATABASE IF NOT EXISTS reddit_karmadb;
CREATE DATABASE IF NOT EXISTS reddit_notificationdb;
CREATE DATABASE IF NOT EXISTS reddit_commentdb;
